FROM python:3.12-bullseye

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app

CMD ["uvicorn", "agent_service.agent_api:app", "--host", "0.0.0.0", "--port", "8001"]